### ISSUE TITLE
Meteor 1.5

### ISSUE THREAD

**Issue by darkadept** [jcoreio/crater#166]
Any thoughts on using Meteor 1.5 vs 1.4.x?

I'm going to see if a simple upgrade works and I'll report my findings here.

**Comment by jedwards1211** [comment]
Ah, I hadn't heard the news yet.  I'll look into it soon.
Btw, a very important change landed yesterday, which reduced duplicate modules and prevents Meteor code must always be run in a fiber" errors.

**Comment by jedwards1211** [comment]
By very important change, I mean one I made to this package

**Comment by darkadept** [comment]
Yes! I saw the change. I've built my app using crater as a base. I've successfully merged everything from your webpack2 branch and all the new stuff from master. I'm not using SSR so I think that helped in making things work a bit better.

Anyways, I did a simple `meteor update` in the meteor folder and then tried to start. Here's the log:

```
yarn start v0.24.6
$ babel-node scripts/start.js 
installing meteor/node_modules...
npm WARN package.json meteor@ No description
npm WARN package.json meteor@ No repository field.
npm WARN package.json meteor@ No README data
npm WARN package.json meteor@ No license field.
babel-runtime@6.23.0 node_modules/babel-runtime
├── regenerator-runtime@0.10.5
└── core-js@2.4.1
building Meteor packages...
installing Meteor npm dependencies...         
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
\
> fibers@1.0.15 install /home/mike/dev/crater3/build/meteor/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /home/mike/dev/crater3/build/meteor/bundle/programs/server
> node npm-rebuild.js

{
  "meteor-dev-bundle": "0.0.0",
  "npm": "2.15.11",
  "ares": "1.10.1-DEV",
  "http_parser": "2.7.0",
  "icu": "56.1",
  "modules": "46",
  "node": "4.8.1",
  "openssl": "1.0.2k",
  "uv": "1.9.1",
  "v8": "4.5.103.46",
  "zlib": "1.2.8"
}
ansi-styles@1.1.0 node_modules/ansi-styles

ansi-regex@0.2.1 node_modules/ansi-regex

chalk@0.5.1 node_modules/chalk

escape-string-regexp@1.0.5 node_modules/escape-string-regexp

has-ansi@0.1.0 node_modules/has-ansi

amdefine@1.0.1 node_modules/amdefine

supports-color@0.2.0 node_modules/supports-color

strip-ansi@0.3.0 node_modules/strip-ansi

eachline@2.3.3 node_modules/eachline

underscore@1.5.2 node_modules/underscore

type-of@2.0.1 node_modules/type-of

asap@2.0.5 node_modules/asap

meteor-promise@0.8.4 node_modules/meteor-promise

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

promise@7.1.1 node_modules/promise

source-map@0.1.32 node_modules/source-map

fibers@1.0.15 node_modules/fibers
Happy[1]: Version: 3.1.0. Using cache? Yes. Threads: 4
Dev server is listening on http://0.0.0.0:4000
Happy[1]: No cache was found, starting fresh.
Happy[1]: All set; signaling webpack to proceed.
webpack building...
  build [=============       ] 65%[smart-restart] can't execute file: /home/mike/dev/crater3/src/index.js
[smart-restart] error given was: Error: Cannot find module '/home/mike/dev/web.browser/program.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.module._load (/home/mike/dev/crater3/node_modules/smart-restart/lib/launcher.js:19:23)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/mike/dev/crater3/build/meteor/bundle/programs/server/boot.js:142:25
    at Array.map (native)
    at Object.specialArgPaths.packages/dynamic-import.js (/home/mike/dev/crater3/build/meteor/bundle/programs/server/boot.js:140:41)
    at /home/mike/dev/crater3/build/meteor/bundle/programs/server/boot.js:306:37
    at Array.forEach (native)
    at Function._.each._.forEach (/home/mike/dev/crater3/build/meteor/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
[smart-restart] further repeats of this error will be suppressed...
Build completed in 3.395s
```

**Comment by darkadept** [comment]
Sorry, that was from a fresh git clone of master.

**Comment by jedwards1211** [comment]
Odd, I wonder if they probably changed the path to `program.json`?  I'll have to investigate later

**Comment by Isarstyle** [comment]
+1 the error still exists , @jedwards1211 is there a solution?

The path has not changed, but somehow the smart restart looses the path to the build_dir, can you update that?


Steps to reproduce: clone crater, meteor update, npm start
`Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
[smart-restart] can't execute file: C:\Meteor\crater\src\index.js
[smart-restart] error given was: Error: Cannot find module 'C:\Meteor\web.browser\program.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.module._load (C:\Meteor\crater\node_modules\smart-restart\lib\launcher.js:19:23)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Meteor\crater\build\meteor\bundle\programs\server\boot.js:142:25
    at Array.map (native)
    at Object.packages/dynamic-import.js (C:\Meteor\crater\build\meteor\bundle\programs\server\boot.js:140:41)
    at C:\Meteor\crater\build\meteor\bundle\programs\server\boot.js:307:37
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Meteor\crater\build\meteor\bundle\programs\server\node_modules\underscore\underscore.js:79:11)
[smart-restart] further repeats of this error will be suppressed...`

**Comment by Isarstyle** [comment]
i have not given up on this, it is working again with meteor 1.6.1 , you just have to add the future package to the root/meteor/package.json, that worked for me. 

Greetings!
