### ISSUE TITLE
Tests aren't running

### ISSUE THREAD

**Issue by darkadept** [jcoreio/crater#98]
I'm cloning a new repo:
```
git clone https://github.com/jcoreio/crater.git
```

Installing packages:
```
npm i
```

And running tests:
```
npm test
```

I'm getting the following error:
```
> crater@2.0.0 test /home/mike/dev/crater
> wdio wdio.conf.js

A service failed in the 'onPrepare' hook
Error: Exit code: null
    at ChildProcess.<anonymous> (/home/mike/dev/crater/node_modules/phantomjs-prebuilt/lib/phantomjs.js:117:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Continue...

=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

[15:29:39]  COMMAND     POST     "/wd/hub/session"
ERROR: Couldn't connect to selenium server
phantomjs
Error: Couldn't connect to selenium server
```

**Comment by jedwards1211** [comment]
Weird, I just tried but I can't reproduce...maybe make sure that port 4444 isn't in use?  (On mac you can run `lsof -i tcp:4444`, not sure about other OSes)

**Comment by darkadept** [comment]
Hmm, I don't have anything on port 4444 (ubuntu linux). But I tried again today and now it's working.

Not sure what happened there. Closing.
